# Generated by Django 4.2.14 on 2026-03-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_founded', models.DateField(blank=True, null=True)),
                ('outside_Europe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Baloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('manifacturer', models.CharField(max_length=100)),
                ('max_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('total_hours', models.IntegerField()),
                ('role', models.CharField(choices=[('JR', 'Junior'), ('MD', 'Medior'), ('SR', 'Senior')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PilotAirline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('take_off_airport', models.CharField(max_length=100)),
                ('landing_airport', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.airline')),
                ('baloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.baloon')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
